// Automatically generated portfolio configuration data.
// Do not edit this file directly unless you know what you are doing.

window.portfolioData = {
  "profile": {
    "name": "Dakshit Gajipara",
    "role": "Jr. Python Developer",
    "company": "Nine Formula Retech LLP",
    "avatar": "./assets/images/ps.png",
    "email": "dakshit.gajipara2707@gmail.com",
    "phone": "+91 94292 93754",
    "birthday": "27 July, 2005",
    "location": "Ahmedabad, Gujarat, India",
    "socials": {
      "linkedin": "https://www.linkedin.com/in/dakshgajipara2707",
      "github": "https://github.com/dakshitpatel27",
      "instagram": "https://www.instagram.com/dakshit_01_?igsh=MWprYXo1aTVxM2x6Ng=="
    }
  },
  "about": {
    "paragraphs": [
      "I am a Python Developer specializing in the Frappe Framework and ERPNext. I have hands-on experience developing and customizing enterprise-grade business applications, currently contributing to real-world real estate ERP and CRM solutions at NineFormula Retech LLP and previously at Sigzen Technologies PVT LTD.",
      "I specialize in building custom Frappe/ERPNext applications, designing custom DocTypes, workflows, automations, reports, notifications, and role-based access controls, while ensuring compliance with Frappe Framework best practices.",
      "With a strong technical foundation in Python, Java, JavaScript, Django, React.js, SQL/MySQL, Data Structures & Algorithms, and REST APIs, I enjoy transforming real-world business requirements into secure, optimized, and scalable software solutions."
    ],
    "services": [
      {
        "title": "ERPNext & Frappe Customization",
        "desc": "Custom DocTypes, workflows, reports, and integrations using the Frappe framework.",
        "icon": "./assets/images/icon-erp.svg"
      },
      {
        "title": "Front-End Development",
        "desc": "Responsive UI using React.js & modern frameworks.",
        "icon": "./assets/images/icon-design.svg"
      },
      {
        "title": "Back-End Development",
        "desc": "Secure & scalable backend using Frappe/ERPNext, Django, Node.js.",
        "icon": "./assets/images/icon-dev.svg"
      },
      {
        "title": "Workflow Automation",
        "desc": "Server-side scripting, background tasks, and business process automation.",
        "icon": "./assets/images/icon-automation.svg"
      },
      {
        "title": "API Development",
        "desc": "REST APIs, authentication & database connectivity.",
        "icon": "./assets/images/icon-app.svg"
      },
      {
        "title": "Database & Data Handling",
        "desc": "MySQL, SQL, Pandas, NumPy for data processing.",
        "icon": "./assets/images/icon-photo.svg"
      }
    ]
  },
  "resume": {
    "downloadLink": "https://drive.google.com/file/d/1TTNkLZzxU1lh8FQ_oncb5DCZsmjXdlf4/view?usp=sharing",
    "experience": [
      {
        "company": "Nine Formula Retech LLP",
        "logo": "./assets/images/NineFormula.png",
        "totalDuration": "Feb 2026 — Present",
        "roles": [
          {
            "title": "Jr. Python Developer",
            "dates": "June 2026 — Present",
            "desc": "Promoted to Jr. Python Developer. Designing and developing robust, scalable backend services, RESTful APIs, and automation systems using Python and Frappe Framework. Collaborating with cross-functional teams to translate business requirements into optimized software solutions."
          },
          {
            "title": "Python Developer Intern",
            "dates": "Feb 2026 — May 2026",
            "desc": "Contributed to custom ERP/CRM application development using the Frappe Framework and Python. Built backend workflows, database logic, custom scripts, and integrated third-party APIs under the mentorship of senior engineers."
          }
        ]
      },
      {
        "company": "Sigzen Technologies PVT LTD",
        "logo": "./assets/images/Sigzen.png",
        "totalDuration": "Nov 2025 — Feb 2026",
        "roles": [
          {
            "title": "Python Developer Intern",
            "dates": "Nov 2025 — Feb 2026",
            "desc": "Worked on Frappe Framework and ERPNext development using Python, including custom app development, backend logic, server-side scripting, API integration, and automation of business workflows."
          }
        ]
      }
    ],
    "education": [
      {
        "school": "LJ Institute of Engineering & Technology - Ahmedabad",
        "logo": "./assets/images/LJ.png",
        "dates": "2022 — 2026",
        "desc": "Bachelor of Engineering in Computer Science & Technology — CGPA: 7.95"
      },
      {
        "school": "12th Grade — Shree Swaminarayan Gurukul-Taravada (GSEB)",
        "logo": "./assets/images/TARAVADA.png",
        "dates": "2022",
        "desc": "Completed HSC (Science Stream)."
      },
      {
        "school": "10th Grade — Shree Swaminarayan Gurukul-Taravada (GSEB)",
        "logo": "./assets/images/TARAVADA.png",
        "dates": "2020",
        "desc": "Completed SSC with 78%."
      }
    ],
    "skills": [
      {
        "name": "Frappe/ERPNext",
        "level": "90"
      },
      {
        "name": "Python / Django",
        "level": "90"
      },
      {
        "name": "HTML / CSS / Bootstrap",
        "level": "75"
      },
      {
        "name": "JavaScript / React.js",
        "level": "80"
      },
      {
        "name": "Java / DSA",
        "level": "70"
      },
      {
        "name": "SQL / MySQL",
        "level": "85"
      }
    ]
  },
  "projects": [
    {
      "title": "Student Performance Tracking System",
      "category": "Python , Frappe & Javascript Development",
      "image": "./assets/images/project-7.jpg",
      "link": "#"
    },
    {
      "title": "Smart Parking Management",
      "category": "ReactJS & Django Development",
      "image": "./assets/images/project-1.jpg",
      "link": "#"
    },
    {
      "title": "Food Delivery System",
      "category": "Python Development",
      "image": "./assets/images/project-2.png",
      "link": "#"
    },
    {
      "title": "Hostel Management System",
      "category": "ReactJS & Django Development",
      "image": "./assets/images/project-3.jpg",
      "link": "#"
    },
    {
      "title": "Weather Information",
      "category": "Front-End Development",
      "image": "./assets/images/project-4.png",
      "link": "https://dakshitpatel27.github.io/Weather-Website/"
    },
    {
      "title": "E-Learning Website",
      "category": "Front-End Development",
      "image": "./assets/images/project-5.png",
      "link": "https://dakshitpatel27.github.io/E-Learning/"
    },
    {
      "title": "Connect 4-Dot Game",
      "category": "Front-End Development",
      "image": "./assets/images/project-6.png",
      "link": "https://dakshitpatel27.github.io/connect4dotgame/"
    }
  ],
  "certifications": [
    {
      "title": "Machine Learning with Python (IBM)",
      "link": "https://coursera.org/verify/U3Y624F3E5IS",
      "badge": "https://www.credly.com/go/0JNOPuyIl14osGmyhxAeVw"
    },
    {
      "title": "Exploratory Data Analysis for ML (IBM)",
      "link": "https://coursera.org/verify/P4JU5VFL77WQ"
    },
    {
      "title": "Introduction to Generative AI (Google Cloud)",
      "link": "https://coursera.org/verify/4RCAWG6WJJAM"
    },
    {
      "title": "Building Generative AI-Powered Applications with Python (IBM)",
      "link": "https://coursera.org/verify/OXUQYVJ9V86A"
    },
    {
      "title": "HTML, CSS, JavaScript for Web Development (John Hopkins University)",
      "link": "https://coursera.org/verify/TWURN77TYYNN"
    },
    {
      "title": "Introduction to Front-End Development (Meta)",
      "link": "https://coursera.org/verify/LUA8JALFCX7S"
    },
    {
      "title": "Inheritance & Data Structures in Java (University of Pennsylvania)",
      "link": "https://coursera.org/verify/BS6JWNFD5TCS"
    },
    {
      "title": "Introduction to Java (LearnQuest)",
      "link": "https://coursera.org/verify/27E7CFHCM6MM"
    },
    {
      "title": "What is Data Science? (IBM)",
      "link": "https://coursera.org/verify/RHMR4FCPQ8X3"
    },
    {
      "title": "Cybersecurity for Everyone (University Of MARYLAND)",
      "link": "https://coursera.org/verify/2B78XVFYZP3X"
    },
    {
      "title": "Foundations of Cybersecurity (Google)",
      "link": "https://coursera.org/verify/M6HWSMX3F6BK"
    },
    {
      "title": "Microsoft Azure Management Tools and Security Solutions (Microsoft)",
      "link": "https://coursera.org/verify/BSG8AUK6M4WK"
    }
  ]
};
