// Automatically generated portfolio configuration data.
// Do not edit this file directly unless you know what you are doing.

window.portfolioData = {
  "profile": {
    "name": "Dakshit Gajipara",
    "role": "Jr. Python Developer",
    "company": "Nine Formula Retech LLP",
    "avatar": "./assets/images/ps.png",
    "email": "dakshit.gajipara2707@gmail.com",
    "phone": "+91 94292 93754",
    "birthday": "27 July, 2005",
    "location": "Ahmedabad, Gujarat, India",
    "socials": {
      "linkedin": "https://www.linkedin.com/in/dakshgajipara2707",
      "github": "https://github.com/dakshitpatel27",
      "instagram": "https://www.instagram.com/dakshit_01_?igsh=MWprYXo1aTVxM2x6Ng=="
    },
    "socialsList": [
      {
        "platform": "linkedin",
        "url": "https://www.linkedin.com/in/dakshgajipara2707"
      },
      {
        "platform": "github",
        "url": "https://github.com/dakshitpatel27"
      },
      {
        "platform": "instagram",
        "url": "https://www.instagram.com/dakshit_01_?igsh=MWprYXo1aTVxM2x6Ng=="
      }
    ],
    "roleAnimationEnabled": true,
    "rolesList": [
      "Jr. Python Developer",
      "Frappe & ERPNext Developer",
      "Backend Engineer",
      "Tech Enthusiast"
    ]
  },
  "about": {
    "paragraphs": [
      "I am a Python Developer specializing in the Frappe Framework and ERPNext. I have hands-on experience developing and customizing enterprise-grade business applications, currently contributing to real-world real estate ERP and CRM solutions at NineFormula Retech LLP and previously at Sigzen Technologies PVT LTD.",
      "I specialize in building custom Frappe/ERPNext applications, designing custom DocTypes, workflows, automations, reports, notifications, and role-based access controls, while ensuring compliance with Frappe Framework best practices.",
      "With a strong technical foundation in Python, Java, JavaScript, Django, React.js, SQL/MySQL, Data Structures & Algorithms, and REST APIs, I enjoy transforming real-world business requirements into secure, optimized, and scalable software solutions."
    ],
    "services": [
      {
        "title": "ERPNext & Frappe Customization",
        "desc": "Custom DocTypes, workflows, reports, and integrations using the Frappe framework.",
        "icon": "./assets/images/icon-erp.svg"
      },
      {
        "title": "Front-End Development",
        "desc": "Responsive UI using React.js & modern frameworks.",
        "icon": "./assets/images/icon-design.svg"
      },
      {
        "title": "Back-End Development",
        "desc": "Secure & scalable backend using Frappe/ERPNext, Django, Node.js.",
        "icon": "./assets/images/icon-dev.svg"
      },
      {
        "title": "Workflow Automation",
        "desc": "Server-side scripting, background tasks, and business process automation.",
        "icon": "./assets/images/icon-automation.svg"
      },
      {
        "title": "API Development",
        "desc": "REST APIs, authentication & database connectivity.",
        "icon": "./assets/images/icon-app.svg"
      },
      {
        "title": "Database & Data Handling",
        "desc": "MySQL, SQL, Pandas, NumPy for data processing.",
        "icon": "./assets/images/icon-photo.svg"
      }
    ]
  },
  "resume": {
    "downloadLink": "https://drive.google.com/file/d/1TTNkLZzxU1lh8FQ_oncb5DCZsmjXdlf4/view?usp=sharing",
    "experience": [
      {
        "company": "Nine Formula Retech LLP",
        "logo": "./assets/images/NineFormula.png",
        "totalDuration": "Feb 2026 — Present",
        "roles": [
          {
            "title": "Jr. Python Developer",
            "dates": "June 2026 — Present",
            "desc": "Promoted to Jr. Python Developer. Designing and developing robust, scalable backend services, RESTful APIs, and automation systems using Python and Frappe Framework. Collaborating with cross-functional teams to translate business requirements into optimized software solutions."
          },
          {
            "title": "Python Developer Intern",
            "dates": "Feb 2026 — May 2026",
            "desc": "Contributed to custom ERP/CRM application development using the Frappe Framework and Python. Built backend workflows, database logic, custom scripts, and integrated third-party APIs under the mentorship of senior engineers."
          }
        ]
      },
      {
        "company": "Sigzen Technologies PVT LTD",
        "logo": "./assets/images/Sigzen.png",
        "totalDuration": "Nov 2025 — Feb 2026",
        "roles": [
          {
            "title": "Python Developer Intern",
            "dates": "Nov 2025 — Feb 2026",
            "desc": "Worked on Frappe Framework and ERPNext development using Python, including custom app development, backend logic, server-side scripting, API integration, and automation of business workflows."
          }
        ]
      }
    ],
    "education": [
      {
        "school": "LJ Institute of Engineering & Technology - Ahmedabad",
        "logo": "./assets/images/LJ.png",
        "dates": "2022 — 2026",
        "desc": "Bachelor of Engineering in Computer Science & Technology — CGPA: 7.95"
      },
      {
        "school": "12th Grade — Shree Swaminarayan Gurukul-Taravada (GSEB)",
        "logo": "./assets/images/TARAVADA.png",
        "dates": "2022",
        "desc": "Completed HSC (Science Stream)."
      },
      {
        "school": "10th Grade — Shree Swaminarayan Gurukul-Taravada (GSEB)",
        "logo": "./assets/images/TARAVADA.png",
        "dates": "2020",
        "desc": "Completed SSC with 78%."
      }
    ],
    "skills": [
      {
        "name": "Frappe/ERPNext",
        "level": "90"
      },
      {
        "name": "Python / Django",
        "level": "90"
      },
      {
        "name": "HTML / CSS / Bootstrap",
        "level": "75"
      },
      {
        "name": "JavaScript / React.js",
        "level": "80"
      },
      {
        "name": "Java / DSA",
        "level": "70"
      },
      {
        "name": "SQL / MySQL",
        "level": "85"
      }
    ]
  },
  "projects": [
    {
      "title": "Student Performance Tracking System",
      "category": "Python , Frappe & Javascript Development",
      "image": "./assets/images/project-7.jpg",
      "link": "#",
      "status": "Completed",
      "featured": false,
      "sortOrder": 0
    },
    {
      "title": "Smart Parking Management",
      "category": "ReactJS & Django Development",
      "image": "./assets/images/project-1.jpg",
      "link": "#",
      "status": "Completed",
      "featured": false,
      "sortOrder": 1
    },
    {
      "title": "Food Delivery System",
      "category": "Python Development",
      "image": "./assets/images/project-2.png",
      "link": "#",
      "status": "Completed",
      "featured": false,
      "sortOrder": 2
    },
    {
      "title": "Hostel Management System",
      "category": "ReactJS & Django Development",
      "image": "./assets/images/project-3.jpg",
      "link": "#",
      "status": "Completed",
      "featured": false,
      "sortOrder": 3
    },
    {
      "title": "Weather Information",
      "category": "Front-End Development",
      "image": "./assets/images/project-4.png",
      "link": "https://dakshitpatel27.github.io/Weather-Website/",
      "status": "Completed",
      "featured": false,
      "sortOrder": 4
    },
    {
      "title": "E-Learning Website",
      "category": "Front-End Development",
      "image": "./assets/images/project-5.png",
      "link": "https://dakshitpatel27.github.io/E-Learning/",
      "status": "Completed",
      "featured": false,
      "sortOrder": 5
    },
    {
      "title": "Connect 4-Dot Game",
      "category": "Front-End Development",
      "image": "./assets/images/project-6.png",
      "link": "https://dakshitpatel27.github.io/connect4dotgame/",
      "status": "Completed",
      "featured": false,
      "sortOrder": 6
    }
  ],
  "achievements": [
    {
      "title": "Hackathon Winner",
      "description": "Secured 1st place in the local university Web3 Hackathon.",
      "date": "March 2026",
      "image": "./assets/images/award.png"
    }
  ],
  "blogs": [
    {
      "title": "Getting Started with Frappe Framework",
      "content": "<p>Frappe is a full-stack, battery-included Python web framework...</p>",
      "tags": "Python, Frappe, ERPNext",
      "image": "./assets/images/blog-1.png",
      "date": "2026-06-14",
      "status": "published"
    }
  ],
  "certifications": [
    {
      "title": "Machine Learning with Python (IBM)",
      "link": "https://coursera.org/verify/U3Y624F3E5IS",
      "badge": "https://www.credly.com/go/0JNOPuyIl14osGmyhxAeVw"
    },
    {
      "title": "Exploratory Data Analysis for ML (IBM)",
      "link": "https://coursera.org/verify/P4JU5VFL77WQ"
    },
    {
      "title": "Introduction to Generative AI (Google Cloud)",
      "link": "https://coursera.org/verify/4RCAWG6WJJAM"
    },
    {
      "title": "Building Generative AI-Powered Applications with Python (IBM)",
      "link": "https://coursera.org/verify/OXUQYVJ9V86A"
    },
    {
      "title": "HTML, CSS, JavaScript for Web Development (John Hopkins University)",
      "link": "https://coursera.org/verify/TWURN77TYYNN"
    },
    {
      "title": "Introduction to Front-End Development (Meta)",
      "link": "https://coursera.org/verify/LUA8JALFCX7S"
    },
    {
      "title": "Inheritance & Data Structures in Java (University of Pennsylvania)",
      "link": "https://coursera.org/verify/BS6JWNFD5TCS"
    },
    {
      "title": "Introduction to Java (LearnQuest)",
      "link": "https://coursera.org/verify/27E7CFHCM6MM"
    },
    {
      "title": "What is Data Science? (IBM)",
      "link": "https://coursera.org/verify/RHMR4FCPQ8X3"
    },
    {
      "title": "Cybersecurity for Everyone (University Of MARYLAND)",
      "link": "https://coursera.org/verify/2B78XVFYZP3X"
    },
    {
      "title": "Foundations of Cybersecurity (Google)",
      "link": "https://coursera.org/verify/M6HWSMX3F6BK"
    },
    {
      "title": "Microsoft Azure Management Tools and Security Solutions (Microsoft)",
      "link": "https://coursera.org/verify/BSG8AUK6M4WK"
    }
  ],
  "settings": {
    "siteOnline": true,
    "siteTitle": "Dakshit Gajipara",
    "siteUrl": "https://dakshit-gajipara.vercel.app",
    "faviconUrl": "./assets/images/logo.ico",
    "web3FormsKey": "1fe4ef89-0663-48b3-92b0-e26621a864b1",
    "metaDescription": "Dakshit Gajipara - Jr. Python Developer specializing in Frappe Framework, ERPNext, Django, and Web Development. View projects, experience, and contact details.",
    "metaKeywords": "Dakshit Gajipara, Python Developer, Frappe Framework, ERPNext, Django, Web Developer, Java, SQL, Portfolio",
    "visibility": {
      "resume": true,
      "projects": true,
      "achievements": true,
      "blogs": true,
      "certifications": true,
      "contact": true
    },
    "background3d": {
      "enabled": true,
      "particleCount": 120,
      "connectionDistance": 110,
      "particleSize": 4.5
    },
    "contactForm": {
      "title": "Get in touch",
      "fields": [
        {
          "type": "text",
          "name": "fullname",
          "placeholder": "Full name",
          "required": true
        },
        {
          "type": "email",
          "name": "email",
          "placeholder": "Email address",
          "required": true
        },
        {
          "type": "tel",
          "name": "phone",
          "placeholder": "Phone number",
          "required": false
        },
        {
          "type": "text",
          "name": "subject",
          "placeholder": "Subject",
          "required": true
        },
        {
          "type": "textarea",
          "name": "message",
          "placeholder": "Your Message",
          "required": true
        }
      ]
    },
    "github": {
      "username": "dakshitpatel27",
      "statsEnabled": true,
      "languagesEnabled": true,
      "theme": "dark"
    },
    "testimonialsEnabled": true,
    "testimonials": [
      {
        "name": "Nirav Patel",
        "role": "Senior Frappe Developer",
        "company": "Nine Formula Retech LLP",
        "avatar": "./assets/images/avatar-1.png",
        "content": "Dakshit is an exceptionally talented Python and Frappe developer. He picks up complex concepts quickly and delivers high-quality work on time."
      },
      {
        "name": "Sanjay Shah",
        "role": "Project Manager",
        "company": "Sigzen Technologies",
        "avatar": "./assets/images/avatar-2.png",
        "content": "Working with Dakshit was a great experience. His dedication to backend workflow automations and database optimizations was highly impressive."
      }
    ]
  },
  "chatbot": {
    "title": "Chat Bot",
    "subtitle": "Online • Ask about me",
    "welcomeMessage": "<p>Hi there! I am <strong>Dakshit's</strong> AI assistant.</p><p>I can help answer questions about his skills, experience, projects, education, or how to contact him. What would you like to know?</p>",
    "suggestions": [
      {
        "label": "👋 About Me",
        "query": "Tell me about yourself"
      },
      {
        "label": "💻 Skills",
        "query": "What are your skills?"
      },
      {
        "label": "🚀 Projects",
        "query": "Show me your projects"
      },
      {
        "label": "💼 Work Experience",
        "query": "Tell me about your experience"
      },
      {
        "label": "🎓 Education",
        "query": "Where did you study?"
      },
      {
        "label": "📜 Certifications",
        "query": "Show me your certifications"
      },
      {
        "label": "📞 Contact Info",
        "query": "How can I contact you?"
      },
      {
        "label": "📄 Download CV",
        "query": "How can I download your CV?"
      }
    ],
    "customQAs": [
      {
        "keywords": "hobbies, hobby, interests",
        "response": "<p>In his free time, Dakshit enjoys reading tech blogs, practicing coding challenges on LeetCode, and exploring open-source projects.</p>"
      },
      {
        "keywords": "frameworks, libraries, backend",
        "response": "<p>Dakshit specializes in the **Frappe Framework** and **ERPNext**. He also has experience working with backend frameworks like **Django** and **Node.js**.</p>"
      }
    ]
  }
};
