const express = require('express');
const fs = require('fs');
const path = require('path');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// Prevent caching of configuration, data, stylesheet, and javascript files
app.use((req, res, next) => {
  if (req.url.includes('config.js') || req.url.includes('data.js') || req.url.includes('style.css') || req.url.includes('script.js')) {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, private');
  }
  next();
});

// Serve static portfolio files
app.use(express.static(__dirname));

// Endpoint to automatically save the portfolio configuration
app.post('/api/save', (req, res) => {
  try {
    const portfolioData = req.body;
    
    if (!portfolioData || typeof portfolioData !== 'object') {
      return res.status(400).json({ success: false, error: 'Invalid data format' });
    }

    const dataJsContent = `// Automatically generated portfolio configuration data.
// Do not edit this file directly unless you know what you are doing.

window.portfolioData = ${JSON.stringify(portfolioData, null, 2)};
`;

    const filePath = path.join(__dirname, 'data.js');
    
    fs.writeFile(filePath, dataJsContent, 'utf8', (err) => {
      if (err) {
        console.error('Failed to write data.js file:', err);
        return res.status(500).json({ success: false, error: 'Failed to write file' });
      }
      console.log('Successfully updated data.js');
      return res.json({ success: true });
    });
  } catch (error) {
    console.error('Error during save operation:', error);
    return res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

// Endpoint to automatically save the API and Password config.js variables
app.post('/api/save-config', (req, res) => {
  try {
    const { api_url, admin_password } = req.body;
    
    const configJsContent = `// Portfolio Remote API Configuration
// ----------------------------------------------------
// If you host your portfolio on Vercel and store your data in Google Drive, 
// paste your deployed Google Apps Script Web App URL below.
//

window.API_URL = "${api_url || ''}";

// Set your Admin Panel password here.
// When accessing admin.html, you will be prompted for this password.
window.ADMIN_PASSWORD = "${admin_password || 'admin123'}";
`;

    const filePath = path.join(__dirname, 'config.js');
    
    fs.writeFile(filePath, configJsContent, 'utf8', (err) => {
      if (err) {
        console.error('Failed to write config.js file:', err);
        return res.status(500).json({ success: false, error: 'Failed to write config.js file' });
      }
      console.log('Successfully updated config.js');
      return res.json({ success: true });
    });
  } catch (error) {
    console.error('Error during config save operation:', error);
    return res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

// Endpoint to check if local server is online
app.get('/api/status', (req, res) => {
  res.json({ success: true, online: true });
});

// Route for clean admin URL
app.get('/admin', (req, res) => {
  res.sendFile(path.join(__dirname, 'admin.html'));
});

// Redirect any unknown route back to index.html
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
  console.log(`\n======================================================`);
  console.log(` Portfolio Admin Server running at:`);
  console.log(` > Website:      http://localhost:${PORT}`);
  console.log(` > Admin Panel:  http://localhost:${PORT}/admin.html`);
  console.log(`======================================================\n`);
});
